Traceback (most recent call last):
  File "person.py", line 271, in <module>
    main()
  File "person.py", line 44, in main
    print("Configurations: ", config)
OSError: [Errno 28] No space left on device
